import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

console.log('DATABASE_URL env value is:', process.env.DATABASE_URL);

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  const plants = [
    {
      id: 1,
      name: 'Fresa',
      category: 'Fruto',
      imageUrl: 'assets/plants/fresa.jpg',
      minTemperature: 18.0,
      maxTemperature: 26.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 8.0,
      minWaterLevel: 70.0,
      minSoilMoisture: 45.0,
      wateringFrequency: 1.0,
    },
    {
      id: 3,
      name: 'Poto',
      category: 'Hoja Verde',
      imageUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=500&auto=format&fit=crop',
      minTemperature: 18.0,
      maxTemperature: 29.0,
      minHumidity: 40.0,
      maxHumidity: 60.0,
      lightHours: 7.0,
      minWaterLevel: 50.0,
      minSoilMoisture: 30.0,
      wateringFrequency: 2.0,
    },
    {
      id: 4,
      name: 'Crassula Muscosa',
      category: 'Suculenta',
      imageUrl: 'assets/plants/crassula_mucosa.jpg',
      minTemperature: 15.0,
      maxTemperature: 24.0,
      minHumidity: 30.0,
      maxHumidity: 50.0,
      lightHours: 8.0,
      minWaterLevel: 40.0,
      minSoilMoisture: 20.0,
      wateringFrequency: 3.0,
    },
    {
      id: 5,
      name: 'Albahaca',
      category: 'Hierba Aromática',
      imageUrl: 'assets/plants/albahaca.jpg',
      minTemperature: 18.0,
      maxTemperature: 25.0,
      minHumidity: 55.0,
      maxHumidity: 75.0,
      lightHours: 9.0,
      minWaterLevel: 65.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 6,
      name: 'Cebollín',
      category: 'Hierba Aromática',
      imageUrl: 'assets/plants/cebollin.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 7.0,
      minWaterLevel: 60.0,
      minSoilMoisture: 40.0,
      wateringFrequency: 2.0,
    },
    {
      id: 7,
      name: 'Cilantro',
      category: 'Hierba Aromática',
      imageUrl: 'assets/plants/cilantro.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 7.0,
      minWaterLevel: 60.0,
      minSoilMoisture: 40.0,
      wateringFrequency: 2.0,
    },
    {
      id: 8,
      name: 'Colrizada',
      category: 'Hoja Verde',
      imageUrl: 'assets/plants/colrizada.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 8.0,
      minWaterLevel: 70.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 9,
      name: 'Espinaca',
      category: 'Hoja Verde',
      imageUrl: 'assets/plants/espinacas.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 8.0,
      minWaterLevel: 70.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 10,
      name: 'Lechuga',
      category: 'Hoja Verde',
      imageUrl: 'assets/plants/lechuga.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 8.0,
      minWaterLevel: 70.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 11,
      name: 'Menta',
      category: 'Hierba Aromática',
      imageUrl: 'assets/plants/menta.jpg',
      minTemperature: 16.0,
      maxTemperature: 24.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 7.0,
      minWaterLevel: 70.0,
      minSoilMoisture: 45.0,
      wateringFrequency: 2.0,
    },
    {
      id: 12,
      name: 'Pepino',
      category: 'Fruto',
      imageUrl: 'assets/plants/pepino.jpg',
      minTemperature: 18.0,
      maxTemperature: 25.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 9.0,
      minWaterLevel: 75.0,
      minSoilMoisture: 55.0,
      wateringFrequency: 1.0,
    },
    {
      id: 13,
      name: 'Perejil',
      category: 'Hierba Aromática',
      imageUrl: 'assets/plants/perejil.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 7.0,
      minWaterLevel: 60.0,
      minSoilMoisture: 40.0,
      wateringFrequency: 2.0,
    },
    {
      id: 14,
      name: 'Pimiento',
      category: 'Fruto',
      imageUrl: 'assets/plants/pimiento.jpg',
      minTemperature: 20.0,
      maxTemperature: 28.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 10.0,
      minWaterLevel: 75.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 15,
      name: 'Rábano',
      category: 'Raíz',
      imageUrl: 'assets/plants/radish.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 7.0,
      minWaterLevel: 65.0,
      minSoilMoisture: 45.0,
      wateringFrequency: 2.0,
    },
    {
      id: 16,
      name: 'Rúcula',
      category: 'Hoja Verde',
      imageUrl: 'assets/plants/arugula.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 7.0,
      minWaterLevel: 65.0,
      minSoilMoisture: 45.0,
      wateringFrequency: 2.0,
    },
    {
      id: 17,
      name: 'Tomate',
      category: 'Fruto',
      imageUrl: 'assets/plants/tomato.jpg',
      minTemperature: 18.0,
      maxTemperature: 27.0,
      minHumidity: 50.0,
      maxHumidity: 70.0,
      lightHours: 9.0,
      minWaterLevel: 75.0,
      minSoilMoisture: 50.0,
      wateringFrequency: 1.0,
    },
    {
      id: 18,
      name: 'Zanahoria',
      category: 'Raíz',
      imageUrl: 'assets/plants/carrot.jpg',
      minTemperature: 15.0,
      maxTemperature: 22.0,
      minHumidity: 60.0,
      maxHumidity: 80.0,
      lightHours: 8.0,
      minWaterLevel: 65.0,
      minSoilMoisture: 45.0,
      wateringFrequency: 2.0,
    },
  ];

  console.log('Iniciando poblamiento de catálogo de plantas...');

  for (const plant of plants) {
    await prisma.plant.upsert({
      where: { id: plant.id },
      update: plant,
      create: plant,
    });
  }

  console.log('¡Catálogo de plantas poblado exitosamente!');
}

main()
  .catch((e) => {
    console.error('Error al poblar la base de datos:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
